server:
  port: 8092
spring:
  application:
    name: "demo-order-service"
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.163.223:8848
      username: nacos
      password: nacos
    sentinel:
      transport:
        port: 8719
        dashboard: 101.43.163.223:8083
      # 每种规则有自己的配置文件
      datasource:
        # 限流的配置
        r1:
          nacos:
            username: nacos
            password: nacos
            server-addr: 101.43.163.223:8848
            data-id: DEMO-SENTINEL-LIMIT
            group-id: DEFAULT_GROUP
            rule-type: flow
        # 熔断的配置
        r2:
          nacos:
            username: nacos
            password: nacos
            server-addr: 101.43.163.223:8848
            data-id: DEMO-SENTINEL-BREAK
            group-id: DEFAULT_GROUP
            rule-type: degrade

seata:
  enabled: true
  application-id: order-server
  tx-service-group: test-save-order-group
  service:
    vgroup-mapping.test-save-order-group: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 101.43.163.223:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      cluster: default