server:
  port: 8092
spring:
  application:
    name: "demo-order-service"
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      username: nacos
      password: nacos
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8083
      # 每种规则有自己的配置文件
      datasource:
        # 限流的配置
        r1:
          nacos:
            username: nacos
            password: nacos
            server-addr: localhost:8848
            data-id: DEMO-SENTINEL-LIMIT
            group-id: DEFAULT_GROUP
            rule-type: flow
        # 熔断的配置
        r2:
          nacos:
            username: nacos
            password: nacos
            server-addr: localhost:8848
            data-id: DEMO-SENTINEL-BREAK
            group-id: DEFAULT_GROUP
            rule-type: degrade
  sleuth:
    sampler:
      # Sleuth采样率，取值范围为[0.1,1.0]，值越大收集越及时，但性能影响也越大
      # 假设在过去的1秒钟order-service实例产生了100个Trace，如果采样率=0.1则代表只有10条记录会被发送到Zipkin服务端进行分析整理
      probability: 1.0
      # 指每秒最多采集量，超出部分将直接抛弃
      rate: 500
  zipkin:
    base-url: http://localhost:9411

seata:
  enabled: true
  application-id: order-server
  tx-service-group: test-save-order-group
  service:
    vgroup-mapping.test-save-order-group: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      cluster: default

logging:
  level:
    com:
      example:
        orderservice: debug