server:
  port: 8092
spring:
  application:
    name: "demo-order-service"
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.163.223:8848
      username: nacos
      password: nacos
    sentinel:
      transport:
        port: 8719
        dashboard: 101.43.163.223:8083

seata:
  enabled: true
  application-id: order-server
  tx-service-group: test-save-order-group
  service:
    vgroup-mapping.test-save-order-group: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 101.43.163.223:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      cluster: default