server:
  port: 8093
spring:
  application:
    name: "demo-shopping-cart-service"
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.163.223:8848
      username: nacos
      password: nacos