server:
  port: 8093
spring:
  application:
    name: "demo-shopping-cart-service"
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.163.223:8848
      username: nacos
      password: nacos

seata:
  enabled: true
  application-id: shopping-cart-server
  tx-service-group: test_save_order_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 101.43.163.223:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      cluster: default