server:
  port: 8093
spring:
  application:
    name: "demo-shopping-cart-service"
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.163.223:8848
      username: nacos
      password: nacos
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: newbee-mall-cloud-goods-datasource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.163.223:3306/newbee_mall_cloud_cart_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: Turing

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

seata:
  enabled: true
  application-id: shopping-cart-server
  tx-service-group: test-save-order-group
  service:
    vgroup-mapping.test-save-order-group: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 101.43.163.223:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      cluster: default